#!/bin/bash

# PostgreSQL Configuration Fix Script
# Fixes invalid shared_buffers and effective_cache_size parameters

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[$(date '+%H:%M:%S')]${NC} $1"; }
success() { echo -e "${GREEN}✓${NC} $1"; }
error() { echo -e "${RED}✗${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root"
    exit 1
fi

log "PostgreSQL Configuration Fix Starting..."

# PostgreSQL paths
PGDATA_DIR="/var/lib/pgsql/data"
POSTGRES_CONF="$PGDATA_DIR/postgresql.conf"

# Stop PostgreSQL service
log "Stopping PostgreSQL service..."
systemctl stop postgresql 2>/dev/null || true

# Check if config file exists
if [ ! -f "$POSTGRES_CONF" ]; then
    error "PostgreSQL configuration file not found at $POSTGRES_CONF"
    exit 1
fi

# Create backup
BACKUP_FILE="$POSTGRES_CONF.backup.$(date +%Y%m%d_%H%M%S)"
log "Creating backup: $BACKUP_FILE"
cp "$POSTGRES_CONF" "$BACKUP_FILE"

# Check for invalid parameters or force fix if config test fails
log "Checking for configuration issues..."
config_needs_fix=false

# Check for specific invalid patterns
if grep -q "shared_buffers.*0.*8kB\|effective_cache_size.*0.*8kB\|shared_buffers.*0\|effective_cache_size.*0" "$POSTGRES_CONF"; then
    log "Found invalid PostgreSQL configuration parameters"
    config_needs_fix=true
fi

# Also check if postgres config test fails
if ! su - postgres -c "postgres --config-file=$POSTGRES_CONF -C shared_buffers" >/dev/null 2>&1; then
    log "PostgreSQL configuration test failed, needs fixing"
    config_needs_fix=true
fi

if [ "$config_needs_fix" = true ]; then
    log "Creating new PostgreSQL configuration..."
    cat > "$POSTGRES_CONF" << 'EOF'
# PostgreSQL Configuration - Fixed for Production
# Generated by fix-postgresql-config.sh

# Connection Settings
listen_addresses = 'localhost'
port = 5432
max_connections = 100

# Memory Settings (Fixed - previously had invalid 0 8kB values)
shared_buffers = 128MB
effective_cache_size = 1GB
maintenance_work_mem = 64MB
work_mem = 4MB

# Write Ahead Log Settings
wal_buffers = 16MB
min_wal_size = 1GB
max_wal_size = 2GB
checkpoint_completion_target = 0.9

# Query Planner Settings
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200

# Worker Process Settings
max_worker_processes = 8
max_parallel_workers_per_gather = 2
max_parallel_workers = 8
max_parallel_maintenance_workers = 2

# Logging Settings
log_destination = 'stderr'
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_rotation_age = 1d
log_rotation_size = 10MB
log_min_messages = warning
log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

# Other Settings
timezone = 'UTC'
datestyle = 'iso, mdy'
default_text_search_config = 'pg_catalog.english'
EOF
    
    success "New configuration created"
else
    log "No invalid parameters found in configuration"
fi

# Set proper ownership and permissions
log "Setting file permissions..."
chown postgres:postgres "$POSTGRES_CONF"
chmod 600 "$POSTGRES_CONF"

# Test configuration with more robust checking
log "Testing PostgreSQL configuration..."

# Test 1: Basic configuration syntax
if su - postgres -c "postgres --config-file=$POSTGRES_CONF --check" >/dev/null 2>&1; then
    success "Configuration syntax check passed"
elif su - postgres -c "postgres --config-file=$POSTGRES_CONF -C shared_buffers" >/dev/null 2>&1; then
    success "Configuration parameter check passed"
else
    log "Configuration test failed, checking what's wrong..."
    
    # Try to get specific error
    config_error=$(su - postgres -c "postgres --config-file=$POSTGRES_CONF -C shared_buffers" 2>&1 || true)
    log "Configuration error: $config_error"
    
    # If it's still a memory parameter issue, force a simpler config
    if echo "$config_error" | grep -q "shared_buffers\|effective_cache_size"; then
        log "Memory parameter issue detected, creating ultra-minimal config..."
        
        cat > "$POSTGRES_CONF" << 'EOF'
# Ultra-minimal PostgreSQL Configuration
listen_addresses = 'localhost'
port = 5432
max_connections = 100
shared_buffers = 32MB
effective_cache_size = 128MB
EOF
        chown postgres:postgres "$POSTGRES_CONF"
        chmod 600 "$POSTGRES_CONF"
        
        # Test ultra-minimal config
        if su - postgres -c "postgres --config-file=$POSTGRES_CONF -C shared_buffers" >/dev/null 2>&1; then
            success "Ultra-minimal configuration works"
        else
            error "Even ultra-minimal configuration failed"
            # Restore backup as last resort
            log "Restoring backup configuration..."
            cp "$BACKUP_FILE" "$POSTGRES_CONF"
            chown postgres:postgres "$POSTGRES_CONF"
            chmod 600 "$POSTGRES_CONF"
            exit 1
        fi
    else
        error "Configuration test failed with unknown error"
        log "Restoring backup configuration..."
        cp "$BACKUP_FILE" "$POSTGRES_CONF"
        chown postgres:postgres "$POSTGRES_CONF"
        chmod 600 "$POSTGRES_CONF"
        exit 1
    fi
fi

# Start PostgreSQL service
log "Starting PostgreSQL service..."
systemctl start postgresql
systemctl enable postgresql

# Wait for service to start
sleep 5

# Check service status
if systemctl is-active --quiet postgresql; then
    success "PostgreSQL service is now running"
    
    # Test database connection
    log "Testing database connection..."
    if su - postgres -c "psql -c 'SELECT version();'" >/dev/null 2>&1; then
        success "Database connection test passed"
        log "PostgreSQL version:"
        su - postgres -c "psql -c 'SELECT version();'" | head -3
    else
        error "Database connection test failed"
        exit 1
    fi
else
    error "PostgreSQL service failed to start"
    systemctl status postgresql
    exit 1
fi

success "PostgreSQL configuration fix completed successfully!"
log "Backup saved at: $BACKUP_FILE"
log "PostgreSQL is now ready for use"